# Generated by Django 5.2.7 on 2026-01-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=20)),
                ('edad', models.PositiveIntegerField()),
                ('adoptado', models.BooleanField(default=False)),
                ('imgMascota', models.ImageField(blank=True, null=True, upload_to='imgMascota/')),
            ],
        ),
    ]
